name: xmonad-javran
version: 0.1.0.0
github:  "Javran/xmonad-javran"
license: MIT
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2014-2020 Javran Cheng"
description: "Javran's xmonad config"

dependencies:
- aeson
- async
- attoparsec
- base
- bytestring
- colour
- containers
- data-default
- deepseq
- directory
- dzen-utils
- filepath
- HaskellNet
- HaskellNet-SSL
- hostname
- json
- lens
- libmpd
- mtl
- process
- scientific
- template-haskell
- text
- time
- unordered-containers
- vector
- xmonad
- xmonad-contrib
- xmonad-entryhelper

library:
  source-dirs: src
  ghc-options:
    - -O2
    - -Wall

executables:
  xmonad-javran:
    source-dirs: exe/xmonad-javran
    main: Main.hs
    dependencies:
      - xmonad-javran
    ghc-options:
      - -threaded
      - -O2
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N

  SysInfoBar:
    source-dirs: exe/SysInfoBar
    main: Main.hs
    dependencies:
      - xmonad-javran
    ghc-options:
      - -threaded
      - -O2
      - -Wall
      - -rtsopts
      - -with-rtsopts=-N
