name: xmonad-javran
version: 0.1.0.0
github:  "Javran/xmonad-javran"
license: MIT
author: "Javran Cheng"
maintainer: "Javran.C@gmail.com"
copyright: "Copyright: (c) 2014-2019 Javran Cheng"
description: "Javran's xmonad config"

dependencies:
- base
- bytestring
- colour
- containers
- data-default
- directory
- dzen-utils
- filepath
- HaskellNet
- HaskellNet-SSL
- json
- lens
- libmpd
- process
- template-haskell
- text
- time
- xmonad
- xmonad-contrib
- xmonad-entryhelper

executables:
  xmonad-javran:
    source-dirs: src
    main: XMonad.Javran.Main
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is XMonad/Javran/Main

  SysInfoBar:
    source-dirs: src
    main: XMonad.Javran.SysInfoBar
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -main-is XMonad/Javran/SysInfoBar
